language: clojure

jobs:
  include:
    - stage: test
      name: "Lein Test"
      script: lein test
      after_success:
        - CLOVERAGE_VERSION=1.0.9 lein cloverage --codecov
        - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
    - stage: deploy
      name: "Clojar Deploy"
      if: tag IS present
      script:
        - lein deploy clojars
